/**
 * Bengaluru localities offered in the /properties Location filter.
 * Property.location itself stays free text in the schema (see
 * prisma/schema.prisma) — this only expands the selectable options so
 * the filter isn't limited to whatever locations the current listings
 * happen to have.
 */
export const BENGALURU_LOCALITIES: string[] = [
  "JP Nagar",
  "Jayanagar",
  "Banashankari",
  "Basavanagudi",
  "BTM Layout",
  "Koramangala",
  "HSR Layout",
  "Indiranagar",
  "Domlur",
  "Ejipura",
  "Bellandur",
  "Sarjapur Road",
  "Whitefield",
  "Marathahalli",
  "Brookefield",
  "Mahadevapura",
  "KR Puram",
  "Hebbal",
  "Yelahanka",
  "Hennur",
  "Kalyan Nagar",
  "HRBR Layout",
  "RT Nagar",
  "Malleshwaram",
  "Rajajinagar",
  "Vijayanagar",
  "Nagarbhavi",
  "Kengeri",
  "Electronic City",
  "Bannerghatta Road",
  "Kanakapura Road",
  "Uttarahalli",
  "Kumaraswamy Layout",
  "Padmanabhanagar",
  "Girinagar",
  "Hosakerehalli",
  "Basaveshwaranagar",
  "Kamakshipalya",
  "Peenya",
  "Sahakar Nagar",
  "Thanisandra",
  "Nagawara",
  "Frazer Town",
  "Cox Town",
  "Cooke Town",
  "Shivajinagar",
  "Richmond Town",
  "Langford Town",
  "Shanti Nagar",
  "Wilson Garden",
  "Ulsoor",
  "CV Raman Nagar",
  "Hoodi",
  "Kadugodi",
  "Varthur",
  "Devanahalli",
];
